### ISSUE TITLE
[ 2375021 ] Key error with log level USER inside threads

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework#109]
The following robot code contains a `USER` log message within a thread

```
IF    1 == 1
    THREAD    DO_THINGS     False
        Log    doing things within a worker thread    USER
    END
END
```

Executed with:` --loglevel=USER`

**Result:**

```
.Exception in thread DO_THINGS:
KeyError: 'DO_THINGS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workplace\RobotFramework\python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\workplace\RobotFramework\python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\workplace\RobotFramework\python39\lib\site-packages\robotframework-6.1-py3.9.egg\robot\running\bodyrunner.py", line 549, in run_worker
    self._context.variables.end_thread()
  File "C:\workplace\RobotFramework\python39\lib\site-packages\robotframework-6.1-py3.9.egg\robot\running\statusreporter.py", line 67, in __exit__
    raise failure
robot.errors.HandlerExecutionFailed: KeyError: 'DO_THINGS'
```

**Comment by test-fullautomation** [comment]
HI @milanac030988  ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
Hello @test-fullautomation ,

It's unable to reproduced. Maybe it was fixed by https://github.com/test-fullautomation/robotframework/pull/119/commits 

Thanks,
Cuong

**Comment by HolQue** [comment]
This is curious. I extended the test code with a '`Sleep`' to make sure that the main thread does not end before the '`DO_THINGS`' thread:

```
    IF    1 == 1
        THREAD    DO_THINGS     False
            Log    doing things within a worker thread    USER
        END
    END

    Sleep    4s
```

I executed with "`--loglevel=USER`". And I got the same error again.

I executed with "`--loglevel=INFO`". And sporadically (~ every 3-5th try) I get:

`[ ERROR ] Reading XML source '...\logfiles\quicktest.robot_INFO.xml' failed: Incompatible child element 'thread' for 'if'.
`
Therefore the already closed https://github.com/test-fullautomation/robotframework/issues/108 is still reproducible also.

**Comment by peppe1337** [comment]
I tried to settle the disagreement above by measuring, because #109 has two opposite answers in it: "unable to reproduce" and "I got the same error again", both from March 2025, both from collaborators.

**Environment:** Linux, Python 3.14, `develop_6.1` at `ae204ad4`, fresh venv. Every report in this thread is Windows / Python 3.9, so a Linux result is a different data point, not a better one.

**Test data:** HolQue's extended snippet verbatim, including the `Sleep`.

## 1. What 90 runs show

30 runs at `--loglevel=USER`, 30 at `--loglevel=INFO`, and 30 control runs:

| | `KeyError` | `Reading XML source ... failed` | `log.html` missing |
|---|---|---|---|
| `--loglevel=USER`, n=30 | 0 | 0 | 0 |
| `--loglevel=INFO`, n=30 | 0 | 0 | 0 |
| control: same file without `THREAD`, `USER`, n=30 | 0 | 0 | 0 |

I checked that my XML checker actually fails on bad input before trusting it: it reports valid XML as valid, a deliberately mismatched tag as invalid, and it does detect `<thread>` under `<if>` when I hand it such a file.

So on this commit and this platform, neither symptom appears. That is not "the bug does not exist" — see section 5.

I should say that I expected the opposite. I wrote down beforehand that the `INFO` runs would show the "Incompatible child element" error in roughly 15–50% of runs, because I read the `THREAD` handling as a write race between the worker and the main thread. That was wrong on both counts: the rate is 0/30, and the mechanism is not a race — see section 3.

## 2. PR #119 is not what fixed the `KeyError`

The guess above was that #119 fixed it. #119 changes **one line in one file**:

```diff
 class BranchHandler(ElementHandler):
     tag = 'branch'
     children = frozenset(('status', 'kw', 'if', 'for', 'try', 'while', 'msg', 'doc',
-                          'return', 'pattern', 'break', 'continue', 'error'))
+                          'return', 'pattern', 'break', 'continue', 'error', 'thread'))
```

That is `src/robot/result/xmlelementhandlers.py` — the XML *reader*. It does not touch `variables/scopes.py`, `running/bodyrunner.py`, or anything on the thread-scope path, so it cannot be the reason the `KeyError` stopped happening. `src/robot/variables/scopes.py` was last changed in `9d9a231` (2024-08-14), which is *before* this issue was filed, and all three accesses to `_thread_scopes` there are membership-guarded today.

## 3. But #119 does explain HolQue's *second* observation, and why it was log-level dependent

The parent element of `<thread>` in `output.xml` depends on the log level. Same `.robot` file, same commit:

```
--loglevel=USER   robot > suite > test > thread
--loglevel=INFO   robot > suite > test > if > branch > thread
```

At `USER`, no `<if>` and no `<branch>` are written at all. At `INFO` they are, and `<thread>` lands inside `<branch>` — which is exactly the element #119 taught the reader to accept. That accounts for the error being log-level dependent: at `USER` the `<thread>` never gets a container that could reject it.

One thing does **not** line up, and I would rather name it than smooth it over: the message quoted above is `Incompatible child element 'thread' for 'if'` — parent `if`, not `branch`. On `ae204ad` I could not produce `<thread>` as a direct child of `<if>` in any run; it is always wrapped in `<branch>` first. So either that build placed the element differently, or the message came from a version older than the `<branch>` wrapper. `IfHandler` still does not accept a `thread` child today, so if anyone can make `<thread>` land directly under `<if>`, that path is still open.

I also checked whether #119 left the same hole open elsewhere, since `for`, `while`, `try` and `if` still do *not* list `thread` as an allowed child. **They don't need to** — FOR and WHILE wrap their bodies in `<iter>` and TRY/IF in `<branch>`, and both of those do allow it. Five runs each at `--loglevel=INFO`, actual parent chains from `output.xml`:

```
for   > iter   > thread     5/5 readable, log.html present
while > iter   > thread     5/5 readable, log.html present
try   > branch > thread     5/5 readable, log.html present
```

Mentioning it so nobody re-checks it.

## 4. One thing that is still off, and it is the same asymmetry

In `XmlLogger`, `start_thread` and `end_thread` are the only control-structure writers with no log-level guard. Of the 42 `start_*`/`end_*` methods in that class, 18 have no guard, and apart from `thread` they are all elements that are written unconditionally by design (`test`, `suite`, `error`, and the statistics/errors sections). Every other body element — `if`, `branch`, `for`, `iter`, `try`, `while`, `break`, `continue`, `return` — is behind `if self._log_message_is_logged(LOG_LEVEL_XML_FILE)`. `kw` is guarded too, but on a level it derives per keyword: for `BuiltIn.Log` it takes the level from the keyword's own arguments rather than from `LOG_LEVEL_XML_FILE`.

The visible consequence is section 3's first line: at `USER` the thread is reported as a direct child of the test, even though it ran inside an `IF`. Nothing crashes today, because `test` accepts a `thread` child — but the reported structure is wrong, and it is the same "the `<thread>` element is written when its container is not" asymmetry that produced the crash #119 had to patch. Given #90 is about reporting on log level `USER`, this may be worth a look there too.

## 5. What I cannot answer

@HolQue's traceback is from `robotframework-6.1-py3.9.egg`, and no commit is named anywhere in the thread. If the `KeyError` still reproduces for you, the commit you were on would decide whether this is fixed or platform-specific — I have no Windows machine to check that side.

**Comment by test-fullautomation** [comment]
Hi @milanac030988 , @HolQue ,
please look into this.
Thank you,
 Thomas
