### ISSUE TITLE
Missing keywords and files when executing Robot Framework atest

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework#36]
Executed: `run.py` with input `robotframework/atest/robot/running/thread` on branch `develop_6.1`.

Result - robot log:

```
INFO - +--- START KEYWORD: Process Output [ ${output} | validate=${validate output} ]
UNKNOWN - No keyword with name 'Process Output' found.
```

Result - xml log:

```
<msg timestamp="20231006 16:52:03.022" level="UNKNOWN">Error in file 'D:\ROBFW\components\robotframework\atest\resources\atest_resource.robot' on line 8: Initializing library 'TestCheckerLibrary' with no arguments failed: URLError: &lt;urlopen error [WinError 3] The system cannot find the path specified: 'D:\\ROBFW\\components\\robotframework\\atest\\doc\\schema\\robot.xsd'&gt;
Traceback (most recent call last):
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 1503, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\ROBFW\\components\\robotframework\\atest\\doc\\schema\\robot.xsd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ROBFW\components\robotframework\atest\resources\TestCheckerLibrary.py", line 102, in __init__
    self.schema = XMLSchema('doc/schema/robot.xsd')
  File "D:\RobotFramework\python39\lib\site-packages\xmlschema\validators\schemas.py", line 343, in __init__
    self.source = XMLResource(source, base_url, allow, defuse, timeout)
  File "D:\RobotFramework\python39\lib\site-packages\xmlschema\resources.py", line 471, in __init__
    self.parse(source, lazy)
  File "D:\RobotFramework\python39\lib\site-packages\xmlschema\resources.py", line 732, in parse
    with urlopen(url, timeout=self._timeout) as resource:
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 1481, in file_open
    return self.open_local_file(req)
  File "D:\RobotFramework\python39\lib\urllib\request.py", line 1520, in open_local_file
    raise URLError(exp)
urllib.error.URLError: &lt;urlopen error [WinError 3] The system cannot find the path specified: 'D:\\ROBFW\\components\\robotframework\\atest\\doc\\schema\\robot.xsd'&gt;</msg>
```

Something not yet checked in?

**Comment by HolQue** [comment]
Ticket is invalid!

Robot Framework atest heavily depends on the current working directory. In my first try with a manual command line I started in the wrong folder, therefore the current working directory was a wrong one also.

The Test Trigger considers to set the current working directory. Executed by test Trigger the threading tests are successful!

I close ticket.

**Comment by test-fullautomation** [comment]
very good!
