### ISSUE TITLE
Issue with unknow status of test result.

### ISSUE THREAD

**Issue by namsonx** [test-fullautomation/robotframework#6]
Hello @milanac030988 ,

     During run acceptance test for testsuites-management package, I found the issue related to UNKOWN state of test result.
     Please find the log below for more information:
=========INFO 01
[ ERROR ] Unexpected error: AttributeError: 'str' object has no attribute 'unknown'
Traceback (most recent call last):
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\utils\application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\run.py", line 450, in main
    result = suite.run(settings)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\running\model.py", line 296, in run
    self.visit(runner)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\model\testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\model\visitor.py", line 88, in visit_suite
    suite.tests.visit(self)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\model\itemlist.py", line 77, in visit
    item.visit(visitor)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\model\testcase.py", line 130, in visit
    visitor.visit_test(self)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\running\suiterunner.py", line 149, in visit_test
    status.test_failed(status.message)
  File "C:\Program Files\RobotFramework\python39\lib\site-packages\robot\running\status.py", line 196, in test_failed
    self.failure.unknown = failure.unknown
Test Case 0101

Thank you,
Son

**Comment by test-fullautomation** [comment]
Hi Cuong,
can you please give me a short status about this issue?
Thank you,
 Thomas

**Comment by milanac030988** [comment]
> 

Hello Thomas,

It was fixed by https://github.com/test-fullautomation/robotframework/commit/0253a0b7794963ecae510dfbf82c7b44fe88fcbb

Thank you,
Cuong
