### ISSUE TITLE
Reporting incomplete on log level USER

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework#90]
A test suite is executed in log level USER. Outcome: The log files contain USER messages only, nothing else (like expected).
We also have no ERRORS and no WARNINGS in this case.

At end of execution I get the following error message:

`[ ERROR ] Reading XML source '.... .robot.xml' failed: Incompatible child element 'msg' for 'suite'.`

The log files in HTML format are missing.

Curious, while developing the log level USER feature I never observed this error. Something must be different now. I currently do not know, what.

**Comment by HolQue** [comment]
Not able to reproduce this error any more.

Whyle trying to recover the original test setup I observed another error.

The following code is executed with log level USER:

```
THREAD    TEST_THREAD_1     False
   Log     ================= I am TEST_THREAD_1    USER    console=no
END

```
Result:

```
Exception in thread TEST_THREAD_1:
KeyError: 'TEST_THREAD_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\workplace\RobotFramework\python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\workplace\RobotFramework\python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\workplace\RobotFramework\python39\lib\site-packages\robotframework-6.1-py3.9.egg\robot\running\bodyrunner.py", line 549, in run_worker
    self._context.variables.end_thread()
  File "C:\workplace\RobotFramework\python39\lib\site-packages\robotframework-6.1-py3.9.egg\robot\running\statusreporter.py", line 67, in __exit__
    raise failure
robot.errors.HandlerExecutionFailed: KeyError: 'TEST_THREAD_1'
```

But all log files are created properly.

**Comment by HolQue** [comment]
I was able to recover the test setup that reproduces the first error. In this setup a Python keyword library is involved.

It seems to me now that we have two different error scenarios:

1. Log keyword with log level USER is used immediately within a robot file.
2. Log keyword with log level USER is used within a Python keyword library.

I will take a deeper look now at option 2.

**Comment by HolQue** [comment]
Retest with v. 0.13.1.20 (extended).

Not able to reproduce the error "_Incompatible child element_" any more.

But observed on another computer.

Waiting for further information about the test setup.

**Comment by HolQue** [comment]
Happened again on another computer. Several errors in the executed test code itself. In the end, something inexplicable happened. Because of a bug in a keyword library, an unchecked shutdown of the Robot Framework caused a crash in this keyword library. All together caused a premature end of test execution and an invalid XML report file.

The errors in the test code are fixed in between. The test execution ends in a proper way. The library bug has no effect in this case (and needs to be fixed separately). Errors did not occur any more. Most probably it will be very difficult to reproduce this scenario.

But nevertheless: Every crash based premature end of test execution might be able to cause corrupt or incomplete XML output files.
